name: Venus Auto Release Build

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: .

      - name: Clean Space Manually
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git wget curl tar zip unzip make binutils bison flex libssl-dev \
            bc libelf-dev gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
            build-essential python3 python3-pip libncurses5-dev libncursesw5-dev \
            pkg-config ccache android-sdk-libsparse-utils vim \
            cpio kmod u-boot-tools xz-utils fdisk util-linux

      - name: Setup Environment
        run: |
          mkdir -p ${{ github.workspace }}/mkbootimg ${{ github.workspace }}/clang ${{ github.workspace }}/dist         
          wget https://android.googlesource.com/platform/system/tools/mkbootimg/+archive/refs/heads/main.tar.gz -O mkb.tar.gz && tar -zxvf mkb.tar.gz -C mkbootimg
          wget https://github.com/GTian5418/LKM_Tools/archive/refs/heads/master.zip && unzip master.zip && mv LKM_Tools-master/*.sh ./ && chmod +x *.sh
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz -O clang.tar.gz && tar -zxvf clang.tar.gz -C clang
          wget https://github.com/GTian5418/android_kernel_qcom_sm8350/archive/refs/heads/lineage-23.1.zip -O kernel.zip && unzip kernel.zip && mv android_kernel_qcom_sm8350-lineage-23.1 k
          wget https://github.com/GTian5418/Venus_Docker_Kernel_Build/releases/download/los23.1/vendor_boot.img
          wget https://github.com/GTian5418/Venus_Docker_Kernel_Build/releases/download/los23.1/vendor_dlkm.img
          wget https://github.com/GTian5418/Venus_Docker_Kernel_Build/releases/download/los23.1/boot.img
          wget https://github.com/GTian5418/AnyKernel3/archive/refs/heads/venus.zip -O Anykernel3.zip && unzip Anykernel3.zip && mv AnyKernel3-venus AnyKernel3
          wget https://github.com/GTian5418/Venus_Docker_Kernel_Build/releases/download/los23.1/magiskboot_alpha.zip && unzip magiskboot_alpha.zip -d magiskboot && rm -rf *.gz *.zip
      - name: Patch Kernel
        run: |
          ls -la ${{ github.workspace }}
          cd ${{ github.workspace }}/k
          sed -i 's/static int selinux_enforcing_boot;/static int selinux_enforcing_boot = 0;/g' security/selinux/hooks.c
          sed -i 's/selinux_enforcing_boot = enforcing ? 1 : 0;/selinux_enforcing_boot = 0;/g' security/selinux/hooks.c
          sed -i 's/#define selinux_enforcing_boot 1/#define selinux_enforcing_boot 0/g' security/selinux/hooks.c
          sed -i 's/return enforcing;/return 0;/g' security/selinux/hooks.c
          cp -f "${{ github.workspace }}/defconfig" "${{ github.workspace }}/k/arch/arm64/configs/defconfig"

      - name: Run Build Script
        run: |
          chmod +x ${{ github.workspace }}/build.sh
          sudo ${{ github.workspace }}/build.sh
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Build-${{ github.run_id }}
          name: Venus Kernel Build ${{ github.run_id }}
          files: |
            dist/*.zip
            dist/*.img
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
